name: Update JLT Map Data

on:
  schedule:
    - cron: '0 4,11,17 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Download JLT GTFS safely using curl
        env:
          TRAFIKLAB_API_KEY: ${{ secrets.TRAFIKLAB_API_KEY }}
        run: |
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" -L "https://opendata.samtrafiken.se/jlt/jlt.zip?key={TRAFIKLAB_API_KEY}" -o jlt.zip

      - name: Run GTFS to GeoJSON Conversion
        run: npx gtfs-to-geojson --configPath config.json

      - name: Commit and Push GeoJSON changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add output/
          git diff-index --quiet HEAD || git commit -m "Automated update of JLT GeoJSON"
          git push
